/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_cyg_learn_jni_LearnJni.h"
#include <string.h>
#include <stdlib.h>
/* Header for class com_cyg_learn_jni_LearnJni */

/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cyg_learn_jni_LearnJni_actionString
  (JNIEnv *env, jobject obj, jstring prompt) {

    char buf[128];
    const char *str;
    str = env->GetStringUTFChars(prompt,NULL);
    if(str == NULL) {
        return;
    }

    env->ReleaseStringUTFChars(prompt,str);

  }

/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionStringSt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cyg_learn_jni_LearnJni_actionStringSt
  (JNIEnv *env, jclass objClass, jstring name) {


  }

/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionArray
 * Signature: ([I)V
 */
JNIEXPORT jint JNICALL Java_com_cyg_learn_jni_LearnJni_actionArray
  (JNIEnv *env, jobject obj, jintArray array) {

//    jint buf[10];
//    jint i ,sum = 0;
//    (*env)->GetIntArrayRegion(env,array,0,10,buf);
//    for(i=0;i<10;i++) {
//        sum += buf[i];
//    }

//    // 第二种访问方式
//    jint *carr;
//    jint i,sum = 0;
//    carr = (*env)->GetIntArrayElements(env,array,NULL);
//    if(carr == NULL) {}
//      return 0;
//    }
//
//    for(i=0;i<10;i++) {
//
//        sum += carr[i];
//    }
//    (*env)->ReleaseIntArrayElements(env,array,carr,0);
//    return sum;
    jint sum = 10;

    return sum;


  }
