/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyg_learn_jni_LoadJni */

#ifndef _Included_com_cyg_learn_jni_LoadJni
#define _Included_com_cyg_learn_jni_LoadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyg_learn_jni_LoadJni
 * Method:    nativeLoadData
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_cyg_learn_jni_LoadJni_nativeLoadData
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
