/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyg_learn_jni_LearnJni */

#ifndef _Included_com_cyg_learn_jni_LearnJni
#define _Included_com_cyg_learn_jni_LearnJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cyg_learn_jni_LearnJni_actionString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionStringSt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cyg_learn_jni_LearnJni_actionStringSt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_cyg_learn_jni_LearnJni
 * Method:    actionArray
 * Signature: ([I)V
 */
JNIEXPORT jint JNICALL Java_com_cyg_learn_jni_LearnJni_actionArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
